# Generated by Django 2.2.24 on 2021-11-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
