# Generated by Django 2.2.24 on 2021-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pins',
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
