# Generated by Django 2.2.24 on 2021-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, null=True)),
                ('sellerid', models.CharField(max_length=20, null=True)),
                ('staffid', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=20, null=True)),
                ('reply', models.CharField(max_length=50, null=True)),
                ('staffid', models.CharField(max_length=20, null=True)),
                ('expressionid', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('storeid', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('messageid', models.CharField(max_length=20, null=True)),
                ('expression', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField(null=True)),
                ('pictere', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerid', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('picture', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='seller',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='picture',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
