# Generated by Django 2.2.24 on 2021-11-25 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20211125_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='expression',
        ),
        migrations.AddField(
            model_name='reply',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
