# Generated by Django 2.2.24 on 2021-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.ImageField(upload_to='pins/')),
            ],
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.IntegerField(choices=[(1, '饮食')], null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
