# Generated by Django 2.2.24 on 2021-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20211201_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.AddField(
            model_name='seller',
            name='m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='n',
            field=models.IntegerField(default=0),
        ),
    ]
