# Generated by Django 2.2.24 on 2021-12-04 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20211202_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=50, null=True, verbose_name='介绍内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sellerid',
            field=models.CharField(max_length=20, null=True, verbose_name='商家Id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='staffid',
            field=models.CharField(max_length=20, null=True, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='expressionid',
            field=models.CharField(max_length=20, null=True, verbose_name='原帖id'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=50, null=True, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='seller',
            field=models.CharField(max_length=20, null=True, verbose_name='商家昵称'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='staffid',
            field=models.CharField(max_length=20, null=True, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='商家邮箱'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='m',
            field=models.IntegerField(default=0, verbose_name='订单消息数'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='n',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='商家昵称'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='商家密码'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='picture',
            field=models.CharField(max_length=20, null=True, verbose_name='商家头像'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[(0, '未登录'), (1, '已登录')], max_length=20, null=True, verbose_name='商家状态'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.IntegerField(choices=[(1, '饮食'), (2, '家电'), (3, '数码'), (4, '清洁用品'), (5, '玩具')], null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='商家用户名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='messageid',
            field=models.CharField(max_length=20, null=True, verbose_name='介绍id'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='商店名字'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='剩余数量'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pictere',
            field=models.CharField(max_length=20, null=True, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='price',
            field=models.CharField(max_length=20, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '缺货'), (3, '已删除')], null=True, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='storeid',
            field=models.CharField(max_length=20, null=True, verbose_name='商店id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='商店名'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.CharField(max_length=20, null=True, verbose_name='商店图片'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sellerid',
            field=models.CharField(max_length=20, null=True, verbose_name='商家id'),
        ),
    ]
