# Generated by Django 2.2.24 on 2021-12-07 00:51

import DjangoUeditor.DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20211204_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='money',
            field=models.FloatField(default=0, verbose_name='赚的钱'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=DjangoUeditor.DjangoUeditor.models.UEditorField(verbose_name='介绍内容'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.IntegerField(choices=[(1, '饮食'), (2, '家电'), (3, '数码'), (4, '清洁用品'), (5, '玩具')], null=True, verbose_name='经营类型'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='price',
            field=models.FloatField(max_length=20, null=True, verbose_name='价格'),
        ),
    ]
