# Generated by Django 2.2.24 on 2021-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_auto_20211207_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='staffid',
            field=models.CharField(max_length=100, null=True, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='picture',
            field=models.CharField(max_length=100, null=True, verbose_name='商家头像'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pictere',
            field=models.CharField(max_length=100, null=True, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.CharField(max_length=100, null=True, verbose_name='商店图片'),
        ),
    ]
