# Generated by Django 2.2.24 on 2021-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_auto_20211207_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='买家昵称'),
        ),
    ]
