# Generated by Django 2.2.24 on 2021-12-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_reply_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='expressionid',
            field=models.IntegerField(max_length=20, null=True, verbose_name='原帖id'),
        ),
    ]
