# Generated by Django 2.2.24 on 2021-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_auto_20211212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('0', '未登录'), ('1', '已登录')], max_length=20, null=True, verbose_name='商家状态'),
        ),
    ]
