# Generated by Django 2.2.24 on 2021-12-14 16:09

import DjangoUeditor.DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20211212_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=DjangoUeditor.DjangoUeditor.models.UEditorField(max_length=1000, verbose_name='介绍内容'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
