# Generated by Django 2.2.24 on 2021-12-19 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0018_auto_20211214_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='用户id')),
                ('address', models.CharField(max_length=20, null=True, verbose_name='用户地址')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.IntegerField(default=0, verbose_name='商品id')),
                ('seller', models.IntegerField(default=0, verbose_name='商家id')),
                ('number', models.CharField(max_length=20, verbose_name='商品数目')),
                ('price', models.FloatField(max_length=20, verbose_name='商品价格')),
                ('store', models.CharField(max_length=20, verbose_name='商店名字')),
                ('name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('pictere', models.CharField(max_length=100, verbose_name='商品图片')),
                ('userid', models.IntegerField(default=0, verbose_name='用户id')),
                ('status', models.IntegerField(choices=[(0, '未购买'), (1, '已购买'), (2, '已删除')], default=0, verbose_name='购物车商品状态')),
                ('buy_number', models.IntegerField(default=1, verbose_name='购买数目')),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('store', models.CharField(max_length=20, verbose_name='商店名称')),
                ('staffid', models.IntegerField(default=0, verbose_name='商品id')),
                ('userid', models.CharField(max_length=20, null=True, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('expression', models.CharField(max_length=300, null=True, verbose_name='评论内容')),
                ('sellerid', models.CharField(max_length=20, null=True, verbose_name='卖家id')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='评论时间')),
                ('status', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='评论是否被回复')),
                ('dell', models.IntegerField(choices=[(0, '评论已被删除'), (1, '正常')], default=1, verbose_name='删除评论')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='用户id')),
                ('user', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('staff', models.IntegerField(default=0, verbose_name='商品id')),
                ('seller', models.IntegerField(default=0, verbose_name='卖家id')),
                ('address', models.CharField(max_length=20, verbose_name='发货地址')),
                ('status', models.IntegerField(choices=[(0, '未发货'), (1, '已发货'), (2, '用户已确认收货'), (3, '申请退货'), (4, '已退货')], default=0, verbose_name='订单状态')),
                ('number', models.CharField(max_length=20, verbose_name='商品数目')),
                ('price', models.FloatField(max_length=20, verbose_name='商品价格')),
                ('store', models.CharField(max_length=20, verbose_name='商店名字')),
                ('name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('pictere', models.CharField(max_length=100, verbose_name='商品图片')),
                ('buy_number', models.IntegerField(default=1, verbose_name='购买数目')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='订单状态更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('email', models.CharField(max_length=20, null=True, verbose_name='用户邮箱')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='用户昵称')),
                ('money', models.FloatField(max_length=20, null=True, verbose_name='用户余额')),
                ('picture', models.CharField(max_length=100, null=True, verbose_name='用户头像')),
                ('status', models.CharField(choices=[('0', '未登录'), ('1', '已登录')], max_length=20, null=True, verbose_name='用户状态')),
                ('buy_status', models.IntegerField(choices=[(0, '冻结购买权限'), (1, '正常')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='His',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='用户id')),
                ('type', models.IntegerField(choices=[(0, '空'), (1, '饮食'), (2, '家电'), (3, '数码'), (4, '清洁用品'), (5, '玩具')], default=0, verbose_name='商品类型')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 12, 19, 15, 20, 8, 831748), verbose_name='浏览时间')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.Staff', verbose_name='商品')),
            ],
        ),
    ]
